config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "home#index"
  resources :categories
  resources :entities

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Category, author: user
    can :manage, Entity, author: user
    can :manage, User, id: user.id
    can :manage, CategoryTransaction, category_id: { author_id: user.id }

    # Define abilities for the passed in user here. For example:
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_transactions, dependent: :destroy, foreign_key: :category_id

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :entity
  belongs_to :category
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_transactions, dependent: :destroy, foreign_key: :entity_id
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy, foreign_key: 'author_id'
  has_many :entities, dependent: :destroy, foreign_key: 'author_id'

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    root_path
  end

  def after_sign_up_path_for(_resource)
    categories_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.includes(category_transactions: :entity)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @category_transactions = @category.category_transactions.includes(:category, :entity)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  # def edit
  # end

  # POST /entities or /entities.json
  def create
    @entity = current_user.entities.new(entity_params)

    if @entity.save
      @category_transaction = @entity.category_transactions.create(category_transactions_params)
      flash[:notice] = 'Transaction was successfully created.'
    else
      flash[:alert] = "Failed to add transaction - #{@entity.errors.full_messages.first}"
    end
    redirect_to "/categories/#{@category_transaction.category_id}"
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  def category_transactions_params
    params.require(:entity).permit(:category_id)
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def total_amount(array)
    total = 0
    array.each do |item|
      total += item.entity.amount
    end
    total
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/_partials/_category_header.html.erb
<div class="card w-100 mt-1">
  <div class="g-0 d-flex align-items-center p-2">
    <div class="w-25">
      <%= image_tag(category.icon, alt: "category icon", class: "category-icon w-20") %>
    </div>
    <div class="w-50 mx-3">
      <div class="card-body">
        <h5 class="display-6 fw-bold text-center"><%= category.name %></h5>
      </div>
    </div>
    <div class="w-25 ml-4 pl-4">
      <h4 class="fw-bold">$ <%= total_amount(@category.category_transactions) %></h4>
    </div>
  </div>
</div>

app/views/_partials/_header.html.erb
<nav class="navbar mobile-header">
  <%= link_to back_path, class: "back-button" do%>
    <span><i class="fa fa-arrow-left"></i></span>
  <% end %>
  <h3 class="header-title fs-5"><%= title %></h3>
  <%= link_to destroy_user_session_path, method: :delete, class: "btn text-light btn-danger" do%>
    <span>Log out</span>
    <i class="fa fa-sign-out"></i>
  <%end%>
</nav>

app/views/_partials/buttons/_add_new_item.html.erb
  <%= link_to new_path, class: "btn btn-add", id: "add" do%>
    <span><%= label.upcase %></span>
  <% end %>

app/views/_partials/cards/_category.html.erb
<div class="card m-3">
  <div class="g-0 category-card justify-content-center d-flex">
    <div class="w-25">
      <%= image_tag(category.icon, alt: "category icon", class: "category-icon") %>
    </div>
    <div class="w-50 mx-3">
      <div class="card-body">
        <h5 class="card-title display-7 fw-bold"><%= category.name %></h5>
      </div>
      <span class="category-date font-italic font-weight-light"><%= category.created_at.strftime("%d/%m/%Y")%></span>
    </div>
    <div class="w-25 m-4 pl-4">
      <h4 class="category-total">$ <%= total_amount(category.category_transactions) %></h4>
    </div>
  </div>
</div>

app/views/_partials/cards/_transaction.html.erb
<div class="card activity-container">
  <div class="g-0 d-flex align-items-center p-2">
        <h3 class="activity-detail">Transaction N°<%= category_transaction.entity.id%></h3>
    <div class="w-50 mx-3">
        <h4 class="activity-body"><%= category_transaction.entity.name %></h5>
    </div>
    <div class="w-50 ml-4 pl-4">
      <h5 class="activity-amount">$ <%= category_transaction.entity.amount %></h4>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, autofocus: true, required: true, placeholder: "Category name", class: "form-control", id: "name" %>
  </div>

  <div class="field">
    <%= form.text_field :icon, required: true, placeholder: "Add icon URL", class: "form-control", id: "icon" %>
  </div>

  <div class="actions mt-5">
    <%= form.submit 'Save Category', class: "btn btn-add"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="catgories-container d-flex flex-column">
  <%= render partial: "_partials/header", locals: { title: "Your Categories", back_path: root_path} %>
  <div class="category-cards text-center">
    <%if @categories.empty? %>
    <h2 class="fw-bold mt-5 display-3">There is no category</h2>
    <p class="mt-3 display-7">Try to add one with the below button</p>
    <%else%>
      <% @categories.each do |category|%>
        <%= link_to category_path(category.id) do%>
          <%= render "_partials/cards/category", category: category%>
        <%end%>
      <%end%>
    <%end%>
  </div>
  <%= render partial: "_partials/buttons/add_new_item", locals: { label: "Add New Category", new_path: new_category_path } %>
</div>

app/views/categories/new.html.erb
<div>
  <%= render partial: "_partials/header", locals: { title: "New Category", back_path: categories_path } %>
  <%= render 'form', category: @category %>
</div>

app/views/categories/show.html.erb
<div>
  <%= render partial: "_partials/header", locals: { title: "Your Transactions", back_path: categories_path} %>
  <%= render partial: "_partials/category_header", locals: { category: @category, category_transactions: @category_transactions } %>

  <div class="text-center">
    <%if @category_transactions.empty? %>
    <h2 class="fw-bold mt-5 display-6">There Is No Transactions</h2>
    <p class="mt-3 display-7">Try to add one with the below button</p>
    <%else%>
      <h2 class="fw-bold mt-5 display-6">Recent Transactions</h2>
      <% @category_transactions.each do |category_transaction|%>
          <%= render partial: "_partials/cards/transaction", locals: { category_transaction: category_transaction } %>
      <%end%>
    <%end%>
  </div>
    <%= render partial: "_partials/buttons/add_new_item", locals: { label: "Add Transaction", new_path: new_entity_path } %>
</div>

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= entity.amount %>
  </p>

</div>

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
  <% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.text_field :name,  autofocus: true, required: true, placeholder: "Transaction Name", class: "form-control", id: "name"  %>
  </div>

  <div class="field">
    <%= form.number_field :amount, required: true, placeholder: "Add amount", class: "form-control", id: "amount"  %>
  </div>

  <div class="form-group">
		<label for="category" class="form-label mr-4 display-5">Category</label>
		<%= form.select :category_id, current_user.categories.map { |category| [category.name, category.id]} ,  {}, { class: "form-select form-select-lg mb-3" }%> 
  </div>

  <div class="actions mt-5">
    <%= form.submit 'Save Transaction', class: "btn btn-add" %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entities</h1>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
    <p>
      <%= link_to "Show this entity", entity %>
    </p>
  <% end %>
</div>

<%= link_to "New entity", new_entity_path %>

app/views/entities/new.html.erb
<div>
  <%= render partial: "_partials/header", locals: { title: "New Transaction", back_path: categories_path } %>
  <%= render 'form', entity: @entity %>
</div>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <%= link_to "Edit this entity", edit_entity_path(@entity) %> |
  <%= link_to "Back to entities", entities_path %>

  <%= button_to "Destroy this entity", @entity, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="bg-image splash-bg shadow-1-strong rounded d-flex justify-content-center align-items-end">
  <div class="sign_in_container text-center">
    <% if user_signed_in? %>
      <h1 class="welcome-title m-5 font-weight-bold">Welcome  <%= current_user.name.capitalize%>, You are signed in</h1>
      <%= link_to 'Go To Categories', categories_path, class: "login-btn btn mb-4 btn-primary", id: "go-categories" %> <br>
      <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "btn btn-danger text-white mb-2" %>
    <%else%>
      <h1 class="m-5">Budget App</h1>
      <%= link_to 'LOG IN', new_user_session_path, class: "btn btn-primary mb-4 py-3" %><br>
      <%= link_to 'SIGN UP', new_user_registration_path, class: "btn btn-success text-white mb-2 py-3" %>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
      <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
      <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%end%>
    <%= yield %>
  </body>
</html>